repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8
        additional_dependencies: [
          "git+https://github.com/PyCQA/pyflakes",
          "git+https://gitlab.com/PyCQA/pycodestyle",
        ]
